# Generated by Django 3.1.3 on 2021-01-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210117_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='image',
            field=models.ImageField(upload_to='app'),
        ),
    ]
