# Generated by Django 3.1.3 on 2021-01-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_produtos_reviewscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='id_usuario',
            new_name='id_cliente',
        ),
    ]
