# Generated by Django 3.1.3 on 2021-01-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210124_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='reviewScore',
            field=models.FloatField(null=True),
        ),
    ]
